# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vogel/Code/LARRI/ARNA_GUI

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vogel/Code/LARRI/ARNA_GUI

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/1216/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vogel/Code/LARRI/ARNA_GUI/CMakeFiles /home/vogel/Code/LARRI/ARNA_GUI/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vogel/Code/LARRI/ARNA_GUI/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ARNA_GUI

# Build rule for target.
ARNA_GUI: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ARNA_GUI
.PHONY : ARNA_GUI

# fast build rule for target.
ARNA_GUI/fast:
	$(MAKE) -f CMakeFiles/ARNA_GUI.dir/build.make CMakeFiles/ARNA_GUI.dir/build
.PHONY : ARNA_GUI/fast

#=============================================================================
# Target rules for targets named rosbridge_lib

# Build rule for target.
rosbridge_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rosbridge_lib
.PHONY : rosbridge_lib

# fast build rule for target.
rosbridge_lib/fast:
	$(MAKE) -f lib/rosbridge_lib/CMakeFiles/rosbridge_lib.dir/build.make lib/rosbridge_lib/CMakeFiles/rosbridge_lib.dir/build
.PHONY : rosbridge_lib/fast

src/ARNA_theora.o: src/ARNA_theora.cpp.o

.PHONY : src/ARNA_theora.o

# target to build an object file
src/ARNA_theora.cpp.o:
	$(MAKE) -f CMakeFiles/ARNA_GUI.dir/build.make CMakeFiles/ARNA_GUI.dir/src/ARNA_theora.cpp.o
.PHONY : src/ARNA_theora.cpp.o

src/ARNA_theora.i: src/ARNA_theora.cpp.i

.PHONY : src/ARNA_theora.i

# target to preprocess a source file
src/ARNA_theora.cpp.i:
	$(MAKE) -f CMakeFiles/ARNA_GUI.dir/build.make CMakeFiles/ARNA_GUI.dir/src/ARNA_theora.cpp.i
.PHONY : src/ARNA_theora.cpp.i

src/ARNA_theora.s: src/ARNA_theora.cpp.s

.PHONY : src/ARNA_theora.s

# target to generate assembly for a file
src/ARNA_theora.cpp.s:
	$(MAKE) -f CMakeFiles/ARNA_GUI.dir/build.make CMakeFiles/ARNA_GUI.dir/src/ARNA_theora.cpp.s
.PHONY : src/ARNA_theora.cpp.s

src/joystick_listener.o: src/joystick_listener.cpp.o

.PHONY : src/joystick_listener.o

# target to build an object file
src/joystick_listener.cpp.o:
	$(MAKE) -f CMakeFiles/ARNA_GUI.dir/build.make CMakeFiles/ARNA_GUI.dir/src/joystick_listener.cpp.o
.PHONY : src/joystick_listener.cpp.o

src/joystick_listener.i: src/joystick_listener.cpp.i

.PHONY : src/joystick_listener.i

# target to preprocess a source file
src/joystick_listener.cpp.i:
	$(MAKE) -f CMakeFiles/ARNA_GUI.dir/build.make CMakeFiles/ARNA_GUI.dir/src/joystick_listener.cpp.i
.PHONY : src/joystick_listener.cpp.i

src/joystick_listener.s: src/joystick_listener.cpp.s

.PHONY : src/joystick_listener.s

# target to generate assembly for a file
src/joystick_listener.cpp.s:
	$(MAKE) -f CMakeFiles/ARNA_GUI.dir/build.make CMakeFiles/ARNA_GUI.dir/src/joystick_listener.cpp.s
.PHONY : src/joystick_listener.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... ARNA_GUI"
	@echo "... edit_cache"
	@echo "... rosbridge_lib"
	@echo "... src/ARNA_theora.o"
	@echo "... src/ARNA_theora.i"
	@echo "... src/ARNA_theora.s"
	@echo "... src/joystick_listener.o"
	@echo "... src/joystick_listener.i"
	@echo "... src/joystick_listener.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

